### ISSUE TITLE
Tasks - Stages 0, 1 e 2

### ISSUE THREAD

**Issue by Pliavi** [Pliavi/Omb3#2]
## Stage 0 - Base API
- [ ] Receber reclamação
- [ ] Postar atualização
- [ ] Finalizar reclamação
- [ ] Gerar token da reclamação para visualização
- [ ] Receber dados da reclamação a partir do token

## Stage 1 - Base View
- [ ] Cadastro reclamação
- [ ] Visualização da reclamação
- [ ] Cadastro de atualização e finalização
- [ ] Visualização pública da reclamação (não pode alterar nada)

## Stage 2 - Setores
- [ ] Separação de setores
  - [ ] Poder passar de privado para público (dentro do sistema)
- [ ] Criar setor
- [ ] Deletar setor
- [ ] Listagem de setor
